version: "3.7"

services:

  server-local:
      build: 
        context: .
        dockerfile: Dockerfile
      ports: 
        - "3000:3000"
      environment:
        DOCKER: 1
      restart: always